import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const sampleProducts = [
        // Sarees (6)
        {
            name: 'Banarasi Silk Saree - Traditional',
            category: 'Saree',
            size: 'Free Size',
            color: 'Red',
            stock: 15,
            costPrice: 3500.00,
            sellingPrice: 6500.00,
            gstPercent: 5,
            imageUrl: null,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            name: 'Kanjeevaram Silk Saree - Temple Border',
            category: 'Saree',
            size: 'Free Size',
            color: 'Maroon',
            stock: 8,
            costPrice: 4200.00,
            sellingPrice: 7800.00,
            gstPercent: 5,
            imageUrl: null,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            name: 'Cotton Saree - Daily Wear',
            category: 'Saree',
            size: 'Free Size',
            color: 'Blue',
            stock: 25,
            costPrice: 800.00,
            sellingPrice: 1400.00,
            gstPercent: 5,
            imageUrl: null,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: 'Designer Georgette Saree - Embroidered',
            category: 'Saree',
            size: 'Free Size',
            color: 'Pink',
            stock: 12,
            costPrice: 2500.00,
            sellingPrice: 4500.00,
            gstPercent: 12,
            imageUrl: null,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            name: 'Pure Silk Saree - Wedding Collection',
            category: 'Saree',
            size: 'Free Size',
            color: 'Green',
            stock: 10,
            costPrice: 3800.00,
            sellingPrice: 7200.00,
            gstPercent: 5,
            imageUrl: null,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            name: 'Chiffon Saree - Party Wear',
            category: 'Saree',
            size: 'Free Size',
            color: 'Purple',
            stock: 18,
            costPrice: 1800.00,
            sellingPrice: 3200.00,
            gstPercent: 12,
            imageUrl: null,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        // Kurtis (5)
        {
            name: 'Anarkali Kurti - Long Flared',
            category: 'Kurti',
            size: 'M',
            color: 'Yellow',
            stock: 22,
            costPrice: 1200.00,
            sellingPrice: 2100.00,
            gstPercent: 12,
            imageUrl: null,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            name: 'Straight Kurti - Cotton with Palazzo',
            category: 'Kurti',
            size: 'L',
            color: 'White',
            stock: 30,
            costPrice: 900.00,
            sellingPrice: 1600.00,
            gstPercent: 12,
            imageUrl: null,
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            name: 'A-Line Kurti - Printed with Leggings',
            category: 'Kurti',
            size: 'XL',
            color: 'Orange',
            stock: 20,
            costPrice: 850.00,
            sellingPrice: 1500.00,
            gstPercent: 12,
            imageUrl: null,
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            name: 'Designer Kurti - Heavy Embroidery',
            category: 'Kurti',
            size: 'M',
            color: 'Black',
            stock: 15,
            costPrice: 1800.00,
            sellingPrice: 3200.00,
            gstPercent: 12,
            imageUrl: null,
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            name: 'Short Kurti - Casual Wear',
            category: 'Kurti',
            size: 'S',
            color: 'Blue',
            stock: 35,
            costPrice: 650.00,
            sellingPrice: 1100.00,
            gstPercent: 12,
            imageUrl: null,
            createdAt: new Date('2024-02-08').toISOString(),
            updatedAt: new Date('2024-02-08').toISOString(),
        },
        // Lehengas (4)
        {
            name: 'Bridal Lehenga - Heavy Zari Work',
            category: 'Lehenga',
            size: 'M',
            color: 'Red',
            stock: 5,
            costPrice: 8500.00,
            sellingPrice: 15000.00,
            gstPercent: 12,
            imageUrl: null,
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            name: 'Party Wear Lehenga - Sequin Work',
            category: 'Lehenga',
            size: 'L',
            color: 'Pink',
            stock: 8,
            costPrice: 4500.00,
            sellingPrice: 8000.00,
            gstPercent: 12,
            imageUrl: null,
            createdAt: new Date('2024-02-12').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
        },
        {
            name: 'Festive Lehenga - Mirror Work',
            category: 'Lehenga',
            size: 'M',
            color: 'Green',
            stock: 10,
            costPrice: 3200.00,
            sellingPrice: 5800.00,
            gstPercent: 12,
            imageUrl: null,
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            name: 'Designer Lehenga - Net with Embroidery',
            category: 'Lehenga',
            size: 'XL',
            color: 'Maroon',
            stock: 7,
            costPrice: 5800.00,
            sellingPrice: 10500.00,
            gstPercent: 12,
            imageUrl: null,
            createdAt: new Date('2024-02-18').toISOString(),
            updatedAt: new Date('2024-02-18').toISOString(),
        },
        // Salwar Suits (3)
        {
            name: 'Patiala Salwar Suit - Cotton',
            category: 'Salwar Suit',
            size: 'L',
            color: 'Yellow',
            stock: 18,
            costPrice: 1400.00,
            sellingPrice: 2500.00,
            gstPercent: 12,
            imageUrl: null,
            createdAt: new Date('2024-02-20').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },
        {
            name: 'Churidar Suit - Silk Blend',
            category: 'Salwar Suit',
            size: 'M',
            color: 'Purple',
            stock: 14,
            costPrice: 1800.00,
            sellingPrice: 3200.00,
            gstPercent: 12,
            imageUrl: null,
            createdAt: new Date('2024-02-22').toISOString(),
            updatedAt: new Date('2024-02-22').toISOString(),
        },
        {
            name: 'Anarkali Suit Set - Designer Collection',
            category: 'Salwar Suit',
            size: 'XL',
            color: 'Blue',
            stock: 12,
            costPrice: 2200.00,
            sellingPrice: 4000.00,
            gstPercent: 12,
            imageUrl: null,
            createdAt: new Date('2024-02-25').toISOString(),
            updatedAt: new Date('2024-02-25').toISOString(),
        },
        // Dress Materials (2)
        {
            name: 'Cotton Dress Material - Unstitched',
            category: 'Dress Material',
            size: 'Free Size',
            color: 'Orange',
            stock: 25,
            costPrice: 700.00,
            sellingPrice: 1200.00,
            gstPercent: 5,
            imageUrl: null,
            createdAt: new Date('2024-02-28').toISOString(),
            updatedAt: new Date('2024-02-28').toISOString(),
        },
        {
            name: 'Silk Dress Material - Premium Quality',
            category: 'Dress Material',
            size: 'Free Size',
            color: 'Green',
            stock: 20,
            costPrice: 1500.00,
            sellingPrice: 2700.00,
            gstPercent: 5,
            imageUrl: null,
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});